refactoring + Tmdb api
andrus92/cinemascope pull request #10
Opened 2021-11-16 20:04 UTC by andrus92

**The code has been refactored:**
  1) Improved pop-up windows for movies
  2) Created 2 separate functions to handle click and mouseover events
  3) Added de-registration from events if we change the content of the page

**Imlemented fetching the movies from themoviedb.org**

2021-11-17 07:21 UTC, SirSerje requested changes
Do not store private data at public code (use .env file for this), please
So:
1. Put your private api key into .env file
2. Access to variable with process.env.YOUR_VARIABLE_NAME
3. At the request method, make validation like:
If there is process.env.VARIABLE_NAME > make request, otherwise, return mock

2021-11-17 07:21 UTC, SirSerje commented on src/tmdbApi.js
> +const API_KEY = '&api_key=c1136013db4178c15f6c05580bac0e31';
Use .env file for data like this

2021-11-17 07:21 UTC, SirSerje commented on src/tmdbApi.js
> +const API_URL = BASE_URL +
String literal will look better than concatenation

2021-11-17 07:21 UTC, SirSerje commented on src/index.js
> +    //getMovieContainerDiv().innerText = '⚠️';
Do not commit unused code (stash it locally or make separate branch, if you have a lot of temporary changes)

2021-11-23 21:33 UTC, closed without merging

2021-11-23 21:34 UTC, andrus92 commented
These changes have been merged into main branch via https://github.com/andrus92/cinemascope/pull/13.